### ISSUE TITLE
Mount point not working

### ISSUE THREAD

**Issue by vladns** [sfjro/aufs5-linux#1]
I'm mounting multiple disk partitions to the /media/hdd mount point via systemd (media-hdd.mount):
```
[Unit]
Description=AUFS disk
Requires=media-sdb.mount
Requires=media-sdc.mount
After=media-sdb.mount
After=media-sdc.mount

[Mount]
What=none
Where=/media/hdd
Type=aufs
Options=br=/media/sdb=rw:/media/sdc,create=mfs,sum,nofail

[Install]
WantedBy=multi-user.target
```
The df -h command displays the full volume of the resulting disk (partition). But when I try to go to /media/hdd and view the contents, a message appears:
```
[root@archlinux media]# cd /media/hdd
[root@archlinux hdd]# ls
ls: unable to open directory '.': Operation not allowed
```
If I mount via fstab, the problem remains.
The problem appeared on the Linux kernel 6.6.5. OS Archlinux.

**Comment by sfjro** [comment]
Hello,

vladns:
> ***@***.*** media]# cd /media/hdd
> ***@***.*** hdd]# ls
> ls: unable to open directory '.': Operation not allowed

Thanks for the report.
First of all, give me these info.

(from aufs REAMDE fil)
- linux kernel version
  if your kernel is not plain, for example modified by distributor,
  the url where i can download its source is necessary too.
- aufs version which was printed at loading the module or booting the
  system, instead of the date you downloaded.
- configuration (define/undefine CONFIG_AUFS_xxx)
- kernel configuration or /proc/config.gz (if you have it)
- LSM (linux security module, if you are using)


J. R. Okajima

**Comment by vladns** [comment]
Looks like I should have asked in https://github.com/sfjro/aufs-standalone
I use archlinux, the kernel is what comes with this OS. The assembly is carried out using a slightly modified PKGBUILD (only my changes):
```
makedepends=(
  ...
  # htmldocs
...
source=(
  https://cdn.kernel.org/pub/linux/kernel/v${pkgver%%.*}.x/${_srcname}.tar.{xz,sign}
  $url/releases/download/$_srctag/linux-$_srctag.patch.zst{,.sig}
  config  # the main kernel config file
  aufs6-base.patch
  aufs6-kbuild.patch
  aufs6-mmap.patch
  aufs6-standalone.patch
  vfs-ino.patch
  Kconfig.patch
  regd.c.patch
)
...
prepare() {
  cd $_srcname

  echo "Setting version..."
  echo "-$pkgrel" > localversion.10-pkgrel
  echo "${pkgbase#linux}" > localversion.20-pkgname

  local src
  for src in "${source[@]}"; do
    src="${src%%::*}"
    src="${src##*/}"
    src="${src%.zst}"
    [[ $src = *.patch ]] || continue
    echo "Applying patch $src..."
    patch -Np1 < "../$src"
  done

  echo "Copy directory aufs..."
  cp -ar $startdir/fs/aufs $srcdir/$_srcname/fs/
  cp -ar $startdir/include/uapi/linux $srcdir/$_srcname/include/uapi/
  echo "Setting config..."
  cp ../config .config
  make olddefconfig
  diff -u ../config .config || :

  make -s kernelrelease > version
  echo "Prepared $pkgbase version $(<version)"
}

build() {
  cd $_srcname
  make all
  #make htmldocs
}

```
Before this, my other script is executed, it prepares all the files:

```
#!/usr/bin/env bash

source ./linux_aufs.ver

cd /build

git clone https://gitlab.archlinux.org/archlinux/packaging/packages/linux.git

cp -ar /compil_pkg/build_scripts/linux_kernel/PKGBUILD /build/linux/

sed -i -e "s|pkgver=.*|pkgver=$pkgver|" -e "s|pkgrel=.*|pkgrel=$pkgrel|" /build/linux/PKGBUILD

wget -P /build/linux https://gitlab.archlinux.org/archlinux/packaging/packages/linux/-/raw/main/config

if grep -q "CONFIG_AUFS_FS=m" /build/linux/config; then echo
else sed -i '/# File systems/aCONFIG_AUFS_FS=m' /build/linux/config
fi

git clone https://github.com/sfjro/aufs-standalone.git

cd /build/aufs-standalone
git checkout origin/aufs$aufsver

cp -ar ./aufs6-kbuild.patch /build/linux/
cp -ar ./aufs6-base.patch /build/linux/
cp -ar ./aufs6-mmap.patch /build/linux/
cp -ar ./aufs6-standalone.patch /build/linux/
cp -ar ./vfs-ino.patch /build/linux

mkdir -p /build/linux/fs && cp -ar /build/aufs-standalone/fs/aufs /build/linux/fs/
mkdir -p /build/linux/include/uapi && cp -ar /build/aufs-standalone/include/uapi/linux /build/linux/include/uapi/

cp -ar /compil_pkg/linux-kernel/changed_files/Kconfig.patch /build/linux/
cp -ar /compil_pkg/linux-kernel/changed_files/regd.c.patch /build/linux/

cd /build/linux
makepkg -g >> PKGBUILD
makepkg -C --skippgpcheck
```
linux_aufs.ver:
```
#!/usr/bin/env bash

pkgver=6.6.6.arch1
pkgrel=1
aufsver=6.6
linuxver=6.6.6

```
The problem started with kernel 6.6.5. On 6.6.6 the problem remains.
[config.tar.gz](https://github.com/sfjro/aufs-linux/files/13639777/config.tar.gz)

**Comment by sfjro** [comment]
vladns:
> I use archlinux, the kernel is what comes with this OS. The assembly is carried out using a slightly modified PKGBUILD (only my changes):
	:::
> git clone https://gitlab.archlinux.org/archlinux/packaging/packages/linux.git

Looking at the url, I see the version string 6.6.6.
Assuming your kernel is v6.6.6, the problem may be related to the commit
roadie2 found recently.
https://github.com/sfjro/aufs-standalone/issues/32

I'd suggest you try replacing your fs/stat.c by v6.6.3.


J. R. Okajima

**Comment by vladns** [comment]
Yes, this solves the problem, even for kernel 6.6.7. Will this greatly harm stability? Apparently, this is someone's mistake and this is a fix, a temporary solution.
